In [2]:
from google.colab import files
uploaded = files.upload()

Saving Data_Train.xlsx to Data_Train.xlsx

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
train_df=pd.read_excel('Data_Train.xlsx')
train_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [257]:
from google.colab import files
uploaded = files.upload()

Saving Test_set.xlsx to Test_set (1).xlsx

In [258]:
test_df=pd.read_excel('Test_set.xlsx')
test_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [259]:
final_df = pd.concat([train_df, test_df])
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [260]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.7+ MB

In [261]:
final_df['Date_of_Journey'].str.split('/')[0]

0    [24, 03, 2019]
0     [6, 06, 2019]
Name: Date_of_Journey, dtype: object

In [262]:
final_df['Date_of_Journey'].str.split('/').str[0]

0       24
1        1
2        9
3       12
4       01
        ..
2666     6
2667    27
2668     6
2669     6
2670    15
Name: Date_of_Journey, Length: 13354, dtype: object

In [263]:
#feature engineering
#convert date time format
#split using this "/"
final_df['Date'] = final_df['Date_of_Journey'].str.split('/').str[0]   # Day
final_df['Month'] = final_df['Date_of_Journey'].str.split('/').str[1]  # Month
final_df['Year'] = final_df['Date_of_Journey'].str.split('/').str[2]   # Year

In [264]:
final_df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019

In [266]:
#specifically used lambda function
final_df['Date']=final_df["Date_of_Journey"].apply(lambda x:x.split("/")[0])
final_df['Month']=final_df["Date_of_Journey"].apply(lambda x:x.split("/")[1])
final_df['Year']=final_df["Date_of_Journey"].apply(lambda x:x.split("/")[2])

In [267]:
final_df['Date']=final_df['Date'].astype(int)
final_df['Month']=final_df['Month'].astype(int)
final_df['Year']=final_df['Year'].astype(int)

In [268]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
 11  Date             13354 non-null  int64
 12  Month            13354 non-null  int64
 13  Year             13354 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 2.0+ MB

In [269]:
final_df.drop('Date_of_Journey',axis=1,inplace=True)

In [270]:
final_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019

In [271]:
final_df['Arrival_Time'].str.split(' ').str[0]

0       01:10
1       13:15
2       04:25
3       23:30
4       21:35
        ...
2666    20:25
2667    16:55
2668    04:25
2669    19:15
2670    19:15
Name: Arrival_Time, Length: 13354, dtype: object

In [272]:
final_df['Arrival_Time']=final_df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [273]:
final_df.isnull().sum()

Airline               0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
Date                  0
Month                 0
Year                  0
dtype: int64

In [274]:
final_df[final_df['Route'].isnull()]

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
9039,Air India,Delhi,Cochin,NaN,09:45,09:25,23h 40m,NaN,No info,7480.0,6,5,2019

In [275]:
final_df['Arrival_hour']=final_df["Arrival_Time"].str.split(':').str[0]
final_df['Arrival_minute']=final_df["Arrival_Time"].str.split(':').str[1]

In [276]:
final_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019,01,10

In [277]:
final_df['Arrival_hour']=final_df['Arrival_hour'].astype(int)
final_df['Arrival_minute']=final_df['Arrival_minute'].astype(int)

In [278]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
 13  Arrival_hour     13354 non-null  int64
 14  Arrival_minute   13354 non-null  int64
dtypes: float64(1), int64(5), object(9)
memory usage: 2.1+ MB

In [279]:
final_df.drop('Arrival_Time',axis=1,inplace=True)

In [280]:
final_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10

In [281]:
final_df['Dep_hour']=final_df["Dep_Time"].str.split(':').str[0]
final_df['Dep_minute']=final_df["Dep_Time"].str.split(':').str[1]

In [282]:
final_df['Dep_hour']=final_df['Dep_hour'].astype(int)
final_df['Dep_minute']=final_df['Dep_minute'].astype(int)

In [283]:
final_df.drop('Dep_Time',axis=1,inplace=True)

In [284]:
final_df.head(1)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20

In [285]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13353 non-null  object
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int64
 9   Month            13354 non-null  int64
 10  Year             13354 non-null  int64
 11  Arrival_hour     13354 non-null  int64
 12  Arrival_minute   13354 non-null  int64
 13  Dep_hour         13354 non-null  int64
 14  Dep_minute       13354 non-null  int64
dtypes: float64(1), int64(7), object(7)
memory usage: 2.1+ MB

In [286]:
#how many total stops are there
final_df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [287]:
final_df['Total_Stops'].isnull().sum()

np.int64(1)

In [288]:
final_df['Total_Stops']=final_df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4,'nan':1})

In [289]:
final_df[final_df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480.0,6,5,2019,9,25,9,45

In [290]:
final_df.head(1)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20

In [291]:
final_df.drop('Route',axis=1,inplace=True)

In [292]:
final_df.head(1)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20

In [293]:
final_df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [294]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Duration         13354 non-null  object
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  object
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int64
 8   Month            13354 non-null  int64
 9   Year             13354 non-null  int64
 10  Arrival_hour     13354 non-null  int64
 11  Arrival_minute   13354 non-null  int64
 12  Dep_hour         13354 non-null  int64
 13  Dep_minute       13354 non-null  int64
dtypes: float64(2), int64(7), object(5)
memory usage: 2.0+ MB

In [295]:
final_df['duration_hour'] = final_df['Duration'].str.split(' ').str[0].str.replace('h','')

In [296]:
final_df.head(1)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,duration_hour
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2

In [297]:
final_df['duration_minute'] = final_df['Duration'].str.split(' ').str[1].str.replace('m','')

In [298]:
final_df.drop(6474,axis=0,inplace=True)
final_df.drop(2660,axis=0,inplace=True)

In [299]:
final_df['duration_hour']=final_df['duration_hour'].astype(int)

In [300]:
final_df['duration_hour']*60

0        120
1        420
2       1140
3        300
4        240
        ...
2666    1380
2667     120
2668     360
2669     900
2670     840
Name: duration_hour, Length: 13351, dtype: int64

In [301]:
final_df.drop('Duration',axis=1,inplace=True)

In [302]:
final_df.head(1)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,duration_hour,duration_minute
0,IndiGo,Banglore,New Delhi,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50

In [303]:
final_df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [304]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()

In [305]:
final_df['Airline']=labelencoder.fit_transform(final_df['Airline'])
final_df['Source']=labelencoder.fit_transform(final_df['Source'])
final_df['Destination']=labelencoder.fit_transform(final_df['Destination'])
final_df['Additional_Info']=labelencoder.fit_transform(final_df['Additional_Info'])

In [306]:
final_df.shape

(13351, 15)

In [307]:
final_df.head(2)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,duration_hour,duration_minute
0,3,0,5,0.0,8,3897.0,24,3,2019,1,10,22,20,2,50
1,1,3,0,2.0,8,7662.0,1,5,2019,13,15,5,50,7,25

In [310]:
final_df[['Airline']]

      Airline
0           3
1           1
2           4
3           3
4           3
...       ...
2666        1
2667        3
2668        4
2669        1
2670        6

[13351 rows x 1 columns]

In [311]:
ohe.fit_transform(np.array(final_df['Airline']).reshape(-1,1))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13351 stored elements and shape (13351, 12)>

In [312]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,duration_hour,duration_minute
0,3,0,5,0.0,8,3897.0,24,3,2019,1,10,22,20,2,50
1,1,3,0,2.0,8,7662.0,1,5,2019,13,15,5,50,7,25
2,4,2,1,2.0,8,13882.0,9,6,2019,4,25,9,25,19,NaN
3,3,3,0,1.0,8,6218.0,12,5,2019,23,30,18,5,5,25
4,3,0,5,1.0,8,13302.0,1,3,2019,21,35,16,50,4,45

In [313]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13351 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13351 non-null  int64
 1   Source           13351 non-null  int64
 2   Destination      13351 non-null  int64
 3   Total_Stops      13350 non-null  float64
 4   Additional_Info  13351 non-null  int64
 5   Price            10681 non-null  float64
 6   Date             13351 non-null  int64
 7   Month            13351 non-null  int64
 8   Year             13351 non-null  int64
 9   Arrival_hour     13351 non-null  int64
 10  Arrival_minute   13351 non-null  int64
 11  Dep_hour         13351 non-null  int64
 12  Dep_minute       13351 non-null  int64
 13  duration_hour    13351 non-null  int64
 14  duration_minute  12068 non-null  object
dtypes: float64(2), int64(12), object(1)
memory usage: 1.6+ MB

In [316]:
pd.get_dummies(final_df,columns=["Airline","Source","Destination","Additional_Info"],drop_first=True)

,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_minute,Dep_hour,Dep_minute,duration_hour,...,Destination_5,Additional_Info_1,Additional_Info_2,Additional_Info_3,Additional_Info_4,Additional_Info_5,Additional_Info_6,Additional_Info_7,Additional_Info_8,Additional_Info_9
0,0.0,3897.0,24,3,2019,1,10,22,20,2,...,True,False,False,False,False,False,False,False,True,False
1,2.0,7662.0,1,5,2019,13,15,5,50,7,...,False,False,False,False,False,False,False,False,True,False
2,2.0,13882.0,9,6,2019,4,25,9,25,19,...,False,False,False,False,False,False,False,False,True,False
3,1.0,6218.0,12,5,2019,23,30,18,5,5,...,False,False,False,False,False,False,False,False,True,False
4,1.0,13302.0,1,3,2019,21,35,16,50,4,...,True,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2666,1.0,NaN,6,6,2019,20,25,20,30,23,...,False,False,False,False,False,False,False,False,True,False
2667,0.0,NaN,27,3,2019,16,55,14,20,2,...,False,False,False,False,False,False,False,False,True,False
2668,1.0,NaN,6,3,2019,4,25,21,50,6,...,False,False,False,False,False,False,False,False,True,False
2669,1.0,NaN,6,3,2019,19,15,4,0,15,...,False,False,False,False,False,False,False,False,True,False
2670,1.0,NaN,15,6,2019,19,15,4,55,14,...,False,False,False,False,False,False,False,False,True,False