groupby() — Group and Analyze Data

In [14]:
import pandas as pd
data={
    'country':['south korea','japan','america','germany','brazil','france'],
    'budget':[120000,130000,200000,100000,210000,230000]
}
df=pd.DataFrame(data)
grouped=df.groupby('country')['budget'].mean()
grouped=df.groupby('country')['budget'].sum()
grouped=df.groupby('country')['budget'].count()

print(grouped)

country
america        200000.0
brazil         210000.0
france         230000.0
germany        100000.0
japan          130000.0
south korea    120000.0
Name: budget, dtype: float64

apply() + lambda — Apply Custom Logic

In [29]:
import pandas as pd
data={
    'job' : ['ceo','baker','manager','bookshop'],
    'salary' : [70000,30000,40000,12000]
}
df=pd.DataFrame(data)
df['final salary'] = df['salary'].apply(lambda x: x+x*0.5)
#print(df)
df['result']=df['final salary'].apply(lambda x: 'vip' if x>=100000 else('good' if 60000<=x<=90000 else 'not enough'))
print(df)

        job  salary  final salary      result
0       ceo   70000      105000.0         vip
1     baker   30000       45000.0  not enough
2   manager   40000       60000.0        good
3  bookshop   12000       18000.0  not enough

Handling Missing Data — isnull(), fillna(), dropna()

In [34]:
#df2 = pd.DataFrame({
 #   'Name': ['Ram', 'Priya', 'Kavi', None],
 #   'Score': [85, 90, None, 95]
#})

#print(df2.isnull())
#df2 = df2.fillna({'Name': 'Unknown', 'Score': 0})
#print(df2)

import pandas as pd
data={
    'country':['south korea','japan','america',None,'brazil','france'],
    'budget':[120000,130000,200000,100000,210000,230000]
}
df=pd.DataFrame(data)
print(df.isnull())
#df=df.fillna({'country': 'germany'})
#print(df)
df_cleaned=df.dropna()
print(df_cleaned)

   country  budget
0    False   False
1    False   False
2    False   False
3     True   False
4    False   False
5    False   False
       country  budget
0  south korea  120000
1        japan  130000
2      america  200000
4       brazil  210000
5       france  230000

describe() — Summary Stats (for numeric columns)

In [ ]:
import pandas as pd

data = {
    'Salary': [10000, 15000, 20000, 25000, 30000],
    'Bonus': [1000, 2000, 3000, 4000, 5000]
}

df = pd.DataFrame(data)
print(df.describe())

value_counts() — Frequency Counter

In [ ]:
df = pd.DataFrame({
    'Department': ['IT', 'HR', 'HR', 'Finance', 'IT', 'IT']
})

print(df['Department'].value_counts())

Sorting — sort_values() + sort_index()

In [3]:
import pandas as pd

data = {
    'salary': [680000, 24000, 36000, 4000, 95000],
    'bonus': [7000, 2000, 6000, 9000, 5000]
}

df = pd.DataFrame(data)

print(df.sort_values(by='salary', ascending=False))
print(df.sort_index())

   salary  bonus
0  680000   7000
4   95000   5000
2   36000   6000
1   24000   2000
3    4000   9000
   salary  bonus
0  680000   7000
1   24000   2000
2   36000   6000
3    4000   9000
4   95000   5000

Merging

In [15]:
import pandas as pd
df1 =({
    'id':[1,2,3,4,5],
    'name':['lakshana','keerthana','hemala','kamali','harshini']
})
df2=({
    'id':[1,2,5,8,4],
    'score':[23,34,5,2,1]
})
df1=pd.DataFrame(df1)
df2=pd.DataFrame(df2)
result=pd.merge(df1,df2,on='id',how='inner')
print(result)

   id       name  score
0   1   lakshana     23
1   2  keerthana     34
2   4     kamali      1
3   5   harshini      5

join

In [16]:

df1 = pd.DataFrame({'name': ['Ava', 'Ben', 'Cleo']}, index=[1, 2, 3])
df2 = pd.DataFrame({'score': [90, 85, 78]}, index=[1, 2, 4])

result = df1.join(df2, how='inner')
print(result)

  name  score
1  Ava     90
2  Ben     85

concat()

In [21]:
import pandas as pd

df1 = pd.DataFrame({'name': ['Ava', 'Ben']})
df2 = pd.DataFrame({'name': ['Cleo', 'David']})

#result = pd.concat([df1, df2], ignore_index=True)
#print(result)
df3 = pd.concat([df1, df2], axis=1)
print(df3)

  name   name
0  Ava   Cleo
1  Ben  David